### ISSUE TITLE
Alfabetizar as páginas das bases de de dados

### ISSUE THREAD

**Issue by atarrisse** [colaboradados/colaboradados.github.io#119]
Alfabetirar as bases de dados

**Comment by wylkon** [comment]
Oi, acho que consigo ajudar nessa issue, pelo que eu entendi precisa colocar em ordem alfabética  todos as instituições dentro de `_posts` correto?

**Comment by atarrisse** [comment]
> Oi, acho que consigo ajudar nessa issue, pelo que eu entendi precisa colocar em ordem alfabética todos as instituições dentro de `_posts` correto?

Eu tava pensando em todas as bases (tem as minucipais em `_states`), mas isso já é uma ótima ajuda. Modifiquei a issue pra especificar pro seu trabalho e abrirei outra pras demais ;)
