### ISSUE TITLE
Discursos de deputados

### ISSUE THREAD

**Issue by ivynasantino** [colaboradados/colaboradados.github.io#138]
Olá :) 

Durante minha pesquisa, acabei desenvolvendo um raspador, até então está bem simples, de discursos da Câmara de deputados referente a uma proposição. Atualmente tenho dados já tratados dos discursos da CCJ, Comissão especial e Plenário relacionados a PEC 06/2019, ou mais conhecida como Nova previdência/Reforma da previdência. Dessa forma, gostaria de saber, vocês tem o interesse de ter esse dado disponível na plataforma? Abs!

**Comment by juditecypreste** [comment]
Olá @ivynasantino, tudo bem? Pode incluir o PR com o link da base e do código? Vamos analisar.  Exemplo:
* Discursos de Deputados na Assembléia de Não Sei o Que [1]

No rodapé:
[1] Código utilizado para captura. Autor: Fulano de Tal
