### ISSUE TITLE
Incluir locais onde o Coluna7 pode ser ouvido

### ISSUE THREAD

**Issue by juditecypreste** [colaboradados/colaboradados.github.io#143]
Além da aba no site, o podcast pode ser ouvido nas seguintes plataformas listadas abaixo. Precisamos pensar em como colocar links para todas elas na aba do Podcast.
<img width="319" alt="Sem título" src="https://user-images.githubusercontent.com/36239583/66875668-8bffd980-ef85-11e9-9a1f-d67b5e1eb3f1.png">

**Comment by anapaulamendes** [comment]
Issue duplicada
