### ISSUE TITLE
Adicionar municípios de Rondonia

### ISSUE THREAD

**Issue by adorilson** [colaboradados/colaboradados.github.io#161]
Adicionar, na esfera municipal, as cidades do estado de Roraima:
 
- [ ] Alta Floresta D´oeste
- [ ] Alto Alegre Dos Parecis
- [ ] Alto Paraíso
- [ ] Alvorada D´oeste
- [ ] Ariquemes
- [ ] Buritis
- [ ] Cabixi
- [ ] Cacaulândia
- [ ] Cacoal
- [ ] Campo Novo de Rondônia
- [ ] Candeias do Jamari
- [ ] Castanheiras
- [ ] Cerejeiras
- [ ] Chupinguaia
- [ ] Colorado do Oeste
- [ ] Corumbiara
- [ ] Costa Marques
- [ ] Cujubim
- [ ] Espigão D´oeste
- [ ] Governador Jorge Teixeira
- [ ] Guajará-mirim
- [ ] Itapuã do Oeste
- [ ] Jaru
- [ ] Ji-paraná
- [ ] Machadinho D´oeste
- [ ] Ministro Andreazza
- [ ] Mirante da Serra
- [ ] Monte Negro
- [ ] Nova Brasilândia D´oeste
- [ ] Nova Mamoré
- [ ] Nova União
- [ ] Novo Horizonte do Oeste
- [ ] Ouro Preto do Oeste
- [ ] Parecis
- [ ] Pimenta Bueno
- [ ] Pimenteiras do Oeste
- [x] Porto Velho
- [x] Presidente Médici
- [x] Primavera de Rondônia
- [x] Rio Crespo
- [x] Rolim de Moura
- [x] Santa Luzia D´oeste
- [x] São Felipe D´oeste
- [x] São Francisco do Guaporé
- [x] São Miguel do Guaporé
- [x] Seringueiras
- [x] Teixeirópolis
- [x] Theobroma
- [x] Urupá
- [x] Vale do Anari
- [x] Vale do Paraíso
- [x] Vilhena

Veja o que deve ser adicionado para cada municipio no [Guia de Colaboração](https://github.com/adorilson/colaboradados.github.io/blob/fc2e206c60aa2ed5e2dec83e03c55c3490155fe2/guia_para_colaboracao.md).

Siga também o padrão de formatação de Porto Velho.

**Comment by luchiago** [comment]
Olá @adorilson, acredito que já podemos fechar essa issue, conferi [aqui](https://github.com/colaboradados/colaboradados.github.io/blob/dev/_states/rondonia.md) as bases e o PR [#7](https://github.com/adorilson/colaboradados.github.io/pull/7) e o #153 fecharam ela. O que acha?
