### ISSUE TITLE
Atualizar links de portais que não estão sendo encontrados

### ISSUE THREAD

**Issue by anapaulamendes** [colaboradados/colaboradados.github.io#190]
Problema: Estes portais estão retornando o status code `404`, portanto, estão fora do ar ou seus links foram atualizados.

## Os portais são:

Prefeitura Municipal de Urucará - http://www.transparencia-am.com.br/URUCARA/PM/urucara.php - 404

Portal da Transparência do Município de Caucaia - http://www.caucaia.ce.gov.br/transparencia.php - 404

Portal da Transparência e Dados Abertos do Município de Anápolis - http://www.transparencia.anapolis.go.gov.br/transparencia/dadosAbertos.jsf - 404

Portal da Transparência do Município de Cajazeiras - https://cajazeiras.pb.gov.br/transparencia/ - 404

Portal da Transparência do Município de Londrina - http://www.londrina.pr.gov.br/index.php?option=com_content&view=section&id=23&Itemid=1765 - 404

Portal da Transparência do Município de Maringá - http://venus.maringa.pr.gov.br:9900/portaltransparencia/ - 404

Portal da Transparência do Município de Olinda - http://transparencia.olinda.pe.gov.br/pronimtb/ - 404

Prefeitura de Japeri - http://www.japeri.rj.gov.br/novatransparencia/ - 404

Prefeitura de Quatis - http://colaboradados.com.br/states/transparencia.quatis.rj.gov.bcr - 404

Portal da Transparência do Município de Afonso Bezerra - http://afonsobezerra.rn.gov.br/transp/ - 404

Portal da Transparência do Município de Baraúna - http://barauna.rn.gov.br/transp/ - 404

Portal da Transparência do Município de Extremoz - http://extremoz.rn.gov.br/portal-da-transparencia/ - 404

Portal da Transparência do Município de Santana do Matos - http://santanadomatos.rn.gov.br/transp/ - 404

Portal da Transparência do Município de São José do Campestre - https://www.saojosedocampestrern.com/transparencia - 404

Portal da Transparência do Município de São Pedro - http://transparenciabr.sytes.net/PMSAOPEDRORN/ - 404

Portal de Transparência da Câmara Municipal de Seringueiras - http://transparencia.camaradeseringueiras.ro.gov.br/ - 404

Portal de Transparência da Câmara Municipal de Theobroma - http://transparencia.theobroma.ro.leg.br/ - 404

Portal da Transparência do Município de Boa Vista - http://transparencia.boavista.rr.gov.br/portal/index.php - 404

Portal da Transparência do Município de Itanhaém - http://www2.itanhaem.sp.gov.br/portal_transparencia/ - 404

Portal da Transparência do Município de Ribeirão Preto - http://www.ribeiraopreto.sp.gov.br/transparencia/i30principal.php - 404

Portal da Transparência do Município de Santa Isabel - https://santaisabel.sp.gov.br/pmsiportal/portal-da-transparencia/ - 404

**Comment by niltonheck** [comment]
@anapaulamendes eu posso ajudar nisso. (:

**Comment by iamchicao** [comment]
Posso ajudar!

**Comment by anapaulamendes** [comment]
Olá @niltonheck @FleepBer , um PR foi aberto primeiro para resolver a issue: https://github.com/colaboradados/colaboradados.github.io/pull/191
Vou seguir a ordem de chegada. Muito obrigada pelas contribuições, nos ajudem com outras issues abertas! :smile:

**Comment by anapaulamendes** [comment]
Olá @fffeiip. Um PR foi aberto antes dos seus para resolver a issue. Se o PR que foi feito antes passar terei que fechar os seus, peço desculpa antecipadamente. Não deixe de contribuir com nosso projeto, temos outras issues abertas. :heart:

**Comment by iamchicao** [comment]
@anapaulamendes  Eu consegui fazer alguns, peço desculpas pelo tanto de commit diferentes, mas estou sem minha máquina! Mais tarde passo aqui de novo para ajudar com mais issues.

**Comment by anapaulamendes** [comment]
Ainda faltam:

Portal da Transparência do Município de São José do Campestre - https://www.saojosedocampestrern.com/transparencia - 404

Portal de Transparência da Câmara Municipal de Seringueiras - http://transparencia.camaradeseringueiras.ro.gov.br/ - 404

Portal de Transparência da Câmara Municipal de Theobroma - http://transparencia.theobroma.ro.leg.br/ - 404

**Comment by anapaulamendes** [comment]
Semanário Oficial da Câmara Municipal de João Pessoa - https://cmjp.pb.gov.br/diario-oficial/ - 404
Portal da Transparência do Município de Monte Alegre - https://montealegre.rn.gov.br/transparencia/ - 404

**Comment by mrncstt** [comment]
Links:

Portal de Transparência da Câmara Municipal de Theobroma - https://transparencia.theobroma.ro.gov.br/portaltransparencia/

Portal da Transparência do Município de Monte Alegre 
https://montealegre.rn.gov.br/transparencia/
