### ISSUE TITLE
Criar conteúdo no arquivo de contribuição

### ISSUE THREAD

**Issue by anapaulamendes** [colaboradados/colaboradados.github.io#20]
Explicar como inserir as bases de dados no padrão de contribuição no markdown de cada esfera. O arquivo é CONTRIBUTING.md. Seria legal também mostrar como sincronizar o repositório para não gerar conflitos, mostrar como é o padrão do markdown com um exemplo e criar um padrão para fechar issues para identificar melhor os commits e pull requests.

**Comment by richardnixondev** [comment]
Oi @anapauladsmendes , A explicação sobre a colaboração em MD das bases, seria pra ser descrito no arquivo "CONTRIBUTING.md" ? 
Sobre essa parte do GIT é tranquilo de sincronização é tranquilo (posso escrever lá), sobre o padrão MD e sobre o padrão de fechamento de issues se puderes me ajudar mesmo que indicando materiais de melhores praticas (não tenho experiencia nisto), eu vejo e boto aqui tambem.

**Comment by anapaulamendes** [comment]
A explicação sobre a colaboração em markdown das bases seria no "CONTRIBUTING.md" mesmo. Este template é ótimo a ser seguido: https://gist.github.com/PurpleBooth/b24679402957c63ec426

Pode ser simples e vamos melhorando aos poucos. Inicialmente seria legal conter a explicação de como contribuir mostrando o exemplo do padrão que as bases precisam ser adicionadas.

Sobre as issues, para fazer uma é uma boa prática comentar na issue seu interesse em resolvê-la. Ao resolvê-la, você commita com uma mensagem relacionada a issue.

Por exemplo: "Close issue #30", assim o git irá reconhecer e seu commit estará na issue. Você pode submeter vários commits em apenas um pull request. O ideal é que não haja conflitos.

Sinta-se a vontade para perguntar e entrar em contato que lhe ajudaremos. :smile:

**Comment by richardnixondev** [comment]
Irei submeter uma primeira versão baseada nas suas orientações 👍
