### ISSUE TITLE
Habilitar o uso de HTTPs

### ISSUE THREAD

**Issue by philss** [colaboradados/colaboradados.github.io#206]
Olá pessoal,

Gostei muito da proposta do projeto! Parabéns!

Vi que ele está hospedado no GitHub pages com um domínio próprio e notei que o HTTPs não está habilitado. Habilitar o HTTPs é fácil e pode ajudar o projeto a indexar melhor nos buscadores, além de trazer mais segurança para quem acessa.

Aqui está o guia de configuração: https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https

Se tiverem dúvidas, posso tentar ajudar.

Obrigado!

**Comment by bax-uva** [comment]
Olá, @philss, posso fazer isso.

**Comment by luchiago** [comment]
Olá @bax-uva, ainda está trabalhando nesta issue?

**Comment by philss** [comment]
@bax-uva @luchiago creio que esse trabalho é mais para quem tem poderes administrativos no projeto.

@anapaulamendes pode dar uma olhada, pfv?

**Comment by anapaulamendes** [comment]
Sim, essa issue só poderá ser resolvida por membros do projeto por conta das permissões.
