### ISSUE TITLE
Imagem para os cartões dos estados

### ISSUE THREAD

**Issue by adorilson** [colaboradados/colaboradados.github.io#239]
Nos cartões do estados (espera municipal) poderia ter uma imagem que representasse o estado, tal como a bandeira ou algo assim.

**Comment by andressavldrs** [comment]
Gostaria de trabalhar nessa issue :)

**Comment by adorilson** [comment]
Parece legal para mim.

Vejam o resultado [aqui](https://imgur.com/a/SIwJKm9).
