### ISSUE TITLE
Balanços do projeto

### ISSUE THREAD

**Issue by juditecypreste** [colaboradados/colaboradados.github.io#4]
Precisamos criar uma nova aba no menu do site, que tenha a mesma estrutura da home (onde estão os assuntos das bases). A ideia e criar postagens, usando md tbm, sobre avanços do projeto e os impactos que ele vem causando. Como uma espécie de balanço do mês. A estrutura com apenas a criação de mds será mais simples para alimentação posterior.

**Comment by anapaulamendes** [comment]
Você pode dar mais detalhes sobre como seria essa nova página do site?

**Comment by anapaulamendes** [comment]
Vou pegar essa issue. :octocat:

**Comment by anapaulamendes** [comment]
Done!
