### ISSUE TITLE
Aba de colaboradores

### ISSUE THREAD

**Issue by juditecypreste** [colaboradados/colaboradados.github.io#5]
Criar uma nova aba no menu para registrar o nome de todos os colaboradores. Desta forma, sempre que alguém ajudar com alguma PR, issue ou mandar uma base de dados maneira, vai ter o seu nome figurando na listagem de colaboradores. :)

**Comment by anapaulamendes** [comment]
Você pode dar mais detalhes sobre como seria essa nova página do site?

**Comment by juditecypreste** [comment]
Ela seria encontrada no menu, com uma estrutura simples: Colaboradores e os seus nomes, seguindo a fonte e estrutura das abas do bot e código de conduta

**Comment by richardnixondev** [comment]
@juditecypreste  e @anapauladsmendes , fiz de forma bem simples tentando seguir o padrão do site, se agradar o pr está lá para aprovação.

😃 👍

**Comment by juditecypreste** [comment]
Oi @sirpresident, eu vi que vc fez, ficou muito bom! Mas agora, por conta de outras atualizações, deu um probleminha com a branch. Vou atualizar o alguns microerros que faltam, e assim que ele estiver redondo escrevo aqui para que, se vc puder, me ajude a atualizar.

**Comment by richardnixondev** [comment]
Com certeza @juditecypreste, vamos  conversando..
