### ISSUE TITLE
Melhorar o CONTRIBUTING.md

### ISSUE THREAD

**Issue by anapaulamendes** [colaboradados/colaboradados.github.io#62]
Descrever mais detalhadamente sobre as contribuições.

**Comment by richardnixondev** [comment]
Boa noite @anapauladsmendes , poderia dar maiores informacoes sobre qual tipo de detalhamento seria desejavel?

**Comment by anapaulamendes** [comment]
Oi @sirpresident !!! :smile: 

Precisamos ter uma explicação de como a pessoa insere bases novas no markdown, no caso, o formato organizadinho.

Por exemplo:
Em _posts/2019-01-21-esfera-federal.md
Verifica se uma subcategoria e uma sub-sub-categoria da qual você vai inserir a base já existe, se existir você adiciona a base no formato na sub-categoria ou/e sub-sub-categoria:

`-   **[Nome da Base](link)**: link`
Ex:
`-   **[Portal Brasileiro de Dados Abertos](http://dados.gov.br/)**: http://dados.gov.br/`

Se a subcategoria e/ou sub-sub-categoria não existe cria-se no formato:

A subcategoria:

`## NOME DA SUB-CATEGORIA`
Ex:
`## GOVERNO FEDERAL`

A sub-sub-categoria:

`### Nome da sub-sub-categoria`
Ex:
`### Receita Federal`

Também explicar que na categoria Esfera Municipal está organizada um pouco diferente, pois está separada por estados:

https://github.com/colaboradados/colaboradados.github.io/tree/master/_states

Explicar como é o formato do markdown como o padrão que já está lá, para que as pessoas não insiram em formatos diferentes.

Se houver dúvidas, estou a disposição e vamos melhorando juntos a documentação. De já agradeço! :smile:
