### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by juditecypreste** [colaboradados/colaboradados.github.io#7]
Ainda não descobrimos como colocar uma coisa bem simples: o favicon. Infelizmente ele não 'pega' da forma como colocamos na head, e talvez tenha alguma particularidade no Jekyll que a gente não tenha sacado. Por enquanto, só um papel branco :(

**Comment by anapaulamendes** [comment]
Vou pegar essa issue. :octocat:

**Comment by anapaulamendes** [comment]
Done!
