### ISSUE TITLE
Criar filtros de pesquisa no site

### ISSUE THREAD

**Issue by anapaulamendes** [colaboradados/colaboradados.github.io#87]
Seria legal filtrar os arquivos no site ou até mesmo as bases por palavras-chave.

**Comment by rafaelhenrique** [comment]
Olá @anapaulamendes ... o filtro seria pra aplicar em TODAS as palavras de TODAS as coisas? Não entendi bem.

Já tem algum mecanismo que tenha keyword no site hoje?

(desculpe, não entendi)

**Comment by luchiago** [comment]
Olá @rafaelhenrique. Atualmente o site tem uma search pelos tipos de bases. Seria interessante ter um filtro para cada portal dentro de um tipo de base (exemplo, fazer uma busca nas bases cadastradas na [Esfera Federal](http://colaboradados.com.br/jekyll/update/2019/01/21/esfera-federal.html)). Me avise se ainda estiver interessado em trabalhar nessa issue :wink:
