### ISSUE TITLE
Bug no ícone 'apoie o colaboradados'

### ISSUE THREAD

**Issue by anapaulamendes** [colaboradados/colaboradados.github.io#88]
![](https://i.ibb.co/GsFtYPb/Screenshot-from-2019-07-13-19-57-33.jpg)

**Comment by anapaulamendes** [comment]
![](https://i.ibb.co/93H1pWJ/Screenshot-from-2019-07-13-20-03-50.jpg)

**Comment by arthuralvim** [comment]
Não consegui reproduzir o erro. Ele está aparentemente corrigido.

**Comment by arthuralvim** [comment]
Só deixar registrado que conseguimos replicar o bug. Geralmente ele ocorre quando o usuário está navegando na página (do meio para o fim de alguma página grande), e depois acessar uma nova página qualquer aperta o botão de "voltar" do navegador. Ele então renderiza a página onde o usuário tinha parado anteriormente, fazendo com que o ícone do porquinho fique por cima dos outros elementos.

**Comment by RuanAragao** [comment]
O problema era apenas com a posição inicial do elemento, ele estava recebendo o valor da posição atual do _scroll_ através do `window.pageYOffset`. Ao retornar no histórico, a pagina retorna para a posição em que estava do _scroll_, então se estivesse em "1400", "1400" seria a posição inicial do porquinho. A posição inicial dele deverá ser sempre "0".

**Comment by atarrisse** [comment]
Essa funcionalidade poderia ser revista pra usar `position: sticky`...
