### ISSUE TITLE
Corrigir os textos incluindo a linguagem inclusiva

### ISSUE THREAD

**Issue by anapaulamendes** [colaboradados/colaboradados.github.io#90]

**Comment by bellesamways** [comment]
oiee, vou pegar essa pra mim @anapaulamendes :D

**Comment by anapaulamendes** [comment]
Assinada para você @bellesamways :heart:

**Comment by anapaulamendes** [comment]
Dicas de materiais: 

- https://medium.com/qg-feminista/escrever-com-x-n%C3%A3o-%C3%A9-linguagem-neutra-f40f715c0b29
- https://medium.com/coragem/adotando-a-linguagem-neutra-de-g%C3%AAnero-e509e6e4e06c

**Comment by luchiago** [comment]
Acredito que os PR's feitos já fecham essa issue, o que acha? @anapaulamendes
