### ISSUE TITLE
Adicionar todas as plataformas que o podcast está online

### ISSUE THREAD

**Issue by anapaulamendes** [colaboradados/colaboradados.github.io#91]
Linkagens para todas as plataformas do podcast

**Comment by scheiladev** [comment]
Olá, eu posso contribuir com essa issue. Podes me marcar nela?

**Comment by anapaulamendes** [comment]
Assinada para você, @sstihler :smile:

**Comment by anapaulamendes** [comment]
@sstihler você ainda vai continuar com essa issue?
