### ISSUE TITLE
Melhorar acessibilidade no site

### ISSUE THREAD

**Issue by anapaulamendes** [colaboradados/colaboradados.github.io#92]
Para ser mais inclusivo precisamos melhorar a acessibilidade do site

**Comment by anapaulamendes** [comment]
Dica de material: Palestra da Lívia Gabos sobre acessibilidade: https://slides.com/liviagabos/wordcamp2019#/

**Comment by adorilson** [comment]
Issue relacionada: #154

**Comment by luchiago** [comment]
O PR #124 resolveu a issue?

**Comment by anapaulamendes** [comment]
@luchiago essa issue sempre estará aberta, acessibilidade é um ponto a sempre ser melhorado :smile: 
Se quiser contribuir com ela, fique a vontade!
